apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backstage
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`backstage.vrsf.in`)
      kind: Rule
      services:
        - name: backstage
          port: http-backend
  tls:
    certResolver: letsencrypt
