---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-patroni
  labels:
    app: patroni
subsets:
  - addresses:
      - ip: 10.0.107.10
      - ip: 10.0.107.11
      - ip: 10.0.107.12
    ports:
      - name: metrics
        port: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: ext-patroni
  labels:
    app: patroni
spec:
  ports:
    - name: metrics
      port: 8008
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ext-patroni
  labels:
    prometheus.io/monitor: "true"
spec:
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - prometheus-exporter
  selector:
    matchLabels:
      app: patroni
