grafana:
  enabled: false

commonLabels:
  prometheus.io/monitor: "true"

prometheus:
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 0

  prometheusSpec:
    replicas: 1
    retention: 360d

    resources:
      requests:
        cpu: 200m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 3072Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: csi-nfs
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 100Gi

    podAntiAffinity: soft
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
            app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                    - alpha
                    - charlie
            weight: 100

    alertingEndpoints:
      - apiVersion: v2
        name: alertmanager
        namespace: monitoring
        pathPrefix: /
        port: http

    serviceMonitorSelector:
      matchLabels:
        prometheus.io/monitor: "true"

    podMonitorSelector:
      matchLabels:
        prometheus.io/monitor: "true"

    overrideHonorLabels: true

prometheusOperator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - alpha
                  - charlie
          weight: 100

kubeStateMetrics:
  honorLabels: true

kube-state-metrics:
  honorLabels: true

  prometheus:
    monitor:
      metrics:
        honorLabels: true
      http:
        honorLabels: true

  metricLabelsAllowlist:
    - nodes=[*]
    - namespaces=[*]
    - pods=[*]

alertmanager:
  enabled: false

defaultRules:
  create: false
