spec:
  inputs:
    job_name:
      default: renovate
    stage:
      default: maintenance
    image:
      default: renovate/renovate:41.131-full
    target:
      default: $CI_PROJECT_PATH
    dry_run:
      default: false
      type: boolean
---
default:
  tags:
    - vrs-factory

stages:
  - maintenance

.renovate:base:
  image: $[[ inputs.image ]]
  script:
    - if [[ "$[[ inputs.dry_run ]]" == "true" ]]; then export RENOVATE_DRY_RUN=full; fi
    - renovate "$[[ inputs.target ]]"
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate-cache
    paths:
      - $RENOVATE_CACHE_DIR
  variables:
    LOG_LEVEL: debug
    RENOVATE_BASE_BRANCHES: $CI_DEFAULT_BRANCH
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR
    RENOVATE_CACHE_DIR: $CI_PROJECT_DIR/cache
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_PLATFORM: gitlab
    RENOVATE_REPOSITORY_CACHE: "enabled"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      allow_failure: true
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

"$[[ inputs.job_name ]]":
  stage: $[[ inputs.stage ]]
  extends: [".renovate:base"]
