---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-vrsfactory-config
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: cloudflare/secrets/vrsfactory-tunnel
  refreshAfter: 30s
  destination:
    create: true
    name: cloudflare-vrsfactory-config
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        TOKEN:
          text: |
            {{- printf "%s" (get .Secrets "token") -}}
  rolloutRestartTargets:
    - name: cloudflare-vrsfactory
      kind: Deployment
