---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pocket-id-smtp
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: pocket-id/secrets/config-smtp
  refreshAfter: 30s
  destination:
    name: config-smtp
    create: true
  rolloutRestartTargets:
    - name: pocket-id
      kind: StatefulSet
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pocket-id-app
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: pocket-id/secrets/config-app
  refreshAfter: 30s
  destination:
    name: config-app
    create: true
  rolloutRestartTargets:
    - name: pocket-id
      kind: StatefulSet
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pocket-id-ldap
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: pocket-id/secrets/config-ldap
  refreshAfter: 30s
  destination:
    name: config-ldap
    create: true
  rolloutRestartTargets:
    - name: pocket-id
      kind: StatefulSet
