---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-token
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: traefik/secrets/cloudflare-token
  refreshAfter: 30s
  destination:
    name: cloudflare-token
    create: true
  rolloutRestartTargets:
    - name: traefik
      kind: Deployment
