---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: otf-oidc
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: otf/secrets/oidc
  refreshAfter: 30s
  destination:
    name: otf-oidc
    create: true
  rolloutRestartTargets:
    - name: otf
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: otf-config
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: otf/secrets/config
  refreshAfter: 30s
  destination:
    name: otf-config
    create: true
  rolloutRestartTargets:
    - name: otf
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: otf-postgresql
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: otf/secrets/postgresql
  refreshAfter: 30s
  destination:
    name: otf-postgresql
    create: true
  rolloutRestartTargets:
    - name: otf
      kind: Deployment
