---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-encryption-key
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: n8n/secrets/encryption-key
  refreshAfter: 30s
  destination:
    name: n8n-encryption-key
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        N8N_ENCRYPTION_KEY:
          text: |
            {{- printf "%s" (get .Secrets "value") -}}
  rolloutRestartTargets:
    - name: n8n
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-postgresql
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: n8n/secrets/postgresql
  refreshAfter: 30s
  destination:
    name: n8n-postgresql
    create: true
  rolloutRestartTargets:
    - name: n8n
      kind: Deployment
