---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: &ns argo-system
spec:
  project: default
  source:
    repoURL: git@gitlab.com:vrs-factory/homelab/k8s-crimson.git
    targetRevision: master
    path: manifests/pocket-id
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
