apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
    prometheus.io/monitor: "true"
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitlab-runner
