---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-runner
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: gitlab-runner/secrets/runners/vrs-factory
  refreshAfter: 30s
  destination:
    name: gitlab-runner
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        runner-token:
          text: |
            {{- printf "%s" (get .Secrets "token") -}}
        runner-registration-token:
          text: ""
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: runner-cache
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: gitlab-runner/secrets/cache
  refreshAfter: 30s
  destination:
    name: s3access
    create: true
