---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: &ns argo-system
  labels:
    gitlab.com/project: "74063407"
    gitlab.com/environment: "29950877"
spec:
  project: default
  info:
    - name: Example
      value: https://example.com
    - name: project_id
      value: "74063407"
    - name: environment_id
      value: "29950877"
  source:
    repoURL: git@gitlab.com:vrs-factory/sandbox/example-k8s-app.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
