resources:
  - resources/namespace.yaml
  - resources/ingress-route.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

namespace: &namespace grafana

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.1.2 # https://github.com/grafana/helm-charts/releases?q=grafana-&expanded=true
    releaseName: grafana
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
