apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.n.vrsf.in`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: letsencrypt
