apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-exporter-speedtest
  template:
    metadata:
      labels:
        app: prometheus-exporter-speedtest
    spec:
      containers:
        - name: prometheus-exporter-speedtest
          image: ghcr.io/slapshin/speedtest_exporter:latest
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 15m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 9090
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 100
