---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: repository-k8s-crimson
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: argo-cd/secrets/repositories/k8s-crimson
  refreshAfter: 10s
  destination:
    name: repository-k8s-crimson
    create: true
    labels:
      argocd.argoproj.io/secret-type: repo-creds
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secret
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: argo-cd/secrets/config
  refreshAfter: 10s
  destination:
    name: argocd-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: argo-cd-argocd-server
    - kind: Deployment
      name: argo-cd-argocd-dex-server
    - kind: Deployment
      name: argo-cd-argocd-applicationset-controller
