apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-nfs
  resources:
    requests:
      storage: 5Gi
