---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: grafana/secrets/admin-credentials
  refreshAfter: 30s
  destination:
    name: grafana-admin-credentials
    create: true
  rolloutRestartTargets:
    - name: grafana
      kind: Deployment
