replicaCount: 1

fullnameOverride: prometheus-exporter-mikrotik

serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus.io/monitor: "true"

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    cpu: 20m
    memory: 256Mi

config:
  router:
    existingSecret: mikrotik-router-config
  scrapper:
    existingSecret: mikrotik-scrapper-config

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus-mikrotik-exporter
          topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: prometheus-mikrotik-exporter
