global:
  domain: argo.vrsf.in
  revisionHistoryLimit: 10

  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  affinity: &affinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

crds:
  install: true
  keep: false

configs:
  secret:
    createSecret: false

  params:
    server.insecure: "true"

  cm:
    kustomize.buildOptions: "--enable-helm --enable-alpha-plugins --enable-exec"
    users.anonymous.enabled: "false"
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets,secrets+literal,
      http,https
    oidc.config: |
      name: VRS-Factory
      issuer: https://id.vrs-factory.dev
      clientID: $oidc.clientId
      clientSecret: $oidc.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      logoutURL: https://id.vrs-factory.dev/api/oidc/end-session
    resource.exclusions: |
      ### Internal Kubernetes resources excluded reduce the number of watched events
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      ### Intermediate Certificate Request excluded reduce the number of watched events
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
      ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice
      ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
      - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
        kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest
  rbac:
    policy.csv: |
      p, role:guest, applications, list, *, allow
      p, role:guest, applications, get, *, allow
      g, argocd_admin, role:admin
      g, argocd_viewer, role:readonly
      g, argocd_guest, role:guest

controller:
  resources:
    requests:
      cpu: 50m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1536Mi # 1,5GB
  pdb:
    maxUnavailable: 50%
  metrics: &metricsMonitor
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus.io/monitor: "true"

dex:
  enabled: false

repoServer:
  metrics: *metricsMonitor

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  affinity: *affinity

  autoscaling:
    enabled: true
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

server:
  metrics: *metricsMonitor
  pdb:
    enabled: true
    minAvailable: 1

  extraArgs:
    - --enable-gzip

  resources:
    requests:
      cpu: 30m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  affinity: *affinity

redis:
  metrics: *metricsMonitor

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

applicationSet:
  metrics: *metricsMonitor

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi
